name: Release Create
on:
  workflow_dispatch:

jobs:
  build:
    name: Release Tag Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # Read changelog and read versions etc.
    - name: Check version is mentioned in Changelog.md
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_depth: 10
        path: 'CHANGELOG.md'
    # Check if the newest tag already exists
    - name: Check if tag exist
      uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
      id: check-tag-exists
      with:
        tag:  "v${{ steps.changelog_reader.outputs.version }} release" # following the pattern of vx.x.xx release used in this repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Create Release with artifacts
    - name: Create Kubelogin Release
      id: create_release
      if: ${{ steps.check-tag-exists.outputs.exists == 'false'}}
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name : "v${{ steps.changelog_reader.outputs.version }}"
        name: "v${{ steps.changelog_reader.outputs.version }} release" # following the pattern of vx.x.xx release used in this repo
        body: ${{ steps.changelog_reader.outputs.changes }}
    # Publish Release
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}